const PLACES = [
  {
    "id": 1,
    "name": "Classic-Remise Berlin",
    "address": "Wiebestraße 36 – 37, 10553 Berlin, Allemagne",
    "category": "Auto & insolite",
    "quarter": "Moabit",
    "note": "Ancien dépôt de tramways rempli de voitures anciennes : métal, verrières et détails mécaniques.",
    "photoQuery": "Classic Remise Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 2,
    "name": "Neue Nationalgalerie",
    "address": "Potsdamer Str. 50, 10785 Berlin, Allemagne",
    "category": "Culture & musées",
    "quarter": "Tiergarten",
    "note": "Mies van der Rohe : verre, acier, trame et minimalisme.",
    "photoQuery": "Neue Nationalgalerie Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 3,
    "name": "P 8",
    "address": "Brunolf-Baade-Str. 1, 12529 Schönefeld, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Schönefeld",
    "note": "Structure contemporaine aux abords de BER, intéressante pour les lignes et répétitions.",
    "photoQuery": "P8 Berlin Brandenburg Airport architecture",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 4,
    "name": "Mäusebunker",
    "address": "Krahmerstraße 6, 12207 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Lichterfelde",
    "note": "Brutalisme radical, volumes massifs et silhouettes presque dystopiques.",
    "photoQuery": "Mäusebunker Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 5,
    "name": "Bibliothèque philologique de l'Université libre de Berlin",
    "address": "Habelschwerdter Allee 45, 14195 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Dahlem",
    "note": "La bibliothèque de Norman Foster, surnommée “The Brain”, offre une géométrie organique très graphique.",
    "photoQuery": "Philological Library Free University Berlin The Brain",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 6,
    "name": "Jakob-Kaiser-Haus",
    "address": "Dorotheenstraße 100/101, 10117 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "Architecture parlementaire contemporaine, passerelles, cours et cadrages sur la Spree.",
    "photoQuery": "Jakob Kaiser Haus Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 7,
    "name": "Chancellerie fédérale",
    "address": "Willy-Brandt-Straße 1, 10557 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Tiergarten",
    "note": "Grands volumes blancs, ouvertures monumentales et perspectives institutionnelles.",
    "photoQuery": "Bundeskanzleramt Berlin architecture",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 8,
    "name": "Université technique de Berlin",
    "address": "Straße des 17. Juni 135, 10623 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Charlottenburg",
    "note": "Campus mêlant modernisme, brutalité et grands volumes universitaires.",
    "photoQuery": "Technische Universität Berlin architecture",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 9,
    "name": "Jacob-und-Wilhelm-Grimm-Zentrum",
    "address": "Geschwister-Scholl-Straße 1-3, 10117 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "Bibliothèque très graphique, connue pour son spectaculaire intérieur en gradins.",
    "photoQuery": "Grimm Zentrum Berlin library",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 10,
    "name": "Axel Springer Neubau",
    "address": "Zimmerstraße 50, 10117 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "OMA : immense atrium diagonal, verre et architecture de bureau spectaculaire.",
    "photoQuery": "Axel Springer Neubau Berlin OMA",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 11,
    "name": "Unité d'Habitation of Berlin",
    "address": "Flatowallee 16, 14055 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Westend",
    "note": "Le Corbusier à Berlin : façade modulaire, couleurs et répétition.",
    "photoQuery": "Corbusierhaus Berlin Unite habitation",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 12,
    "name": "the temporary bauhaus-archiv / museum für gestaltung",
    "address": "Knesebeckstraße 1, 10623 Berlin-Bezirk Charlottenburg-Wilmersdorf, Allemagne",
    "category": "Culture & musées",
    "quarter": "Charlottenburg",
    "note": "Adresse temporaire du Bauhaus-Archiv, utile pour suivre ses expositions pendant les travaux.",
    "photoQuery": "temporary bauhaus archiv Berlin Knesebeckstrasse",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 13,
    "name": "Bauhaus Archive",
    "address": "Klingelhöferstraße 14, 10785 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Tiergarten",
    "note": "Icône Bauhaus reconnaissable à ses sheds et sa silhouette industrielle blanche.",
    "photoQuery": "Bauhaus Archiv Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 14,
    "name": "Interbau Apartment House / Oscar Niemeyer",
    "address": "Altonaer Str. 6, 10557 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Hansaviertel",
    "note": "Immeuble Interbau de Niemeyer : pilotis, façade rythmée et modernisme des années 1950.",
    "photoQuery": "Oscar Niemeyer Haus Berlin Hansaviertel",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 15,
    "name": "Berlin-Hansaviertel",
    "address": "Altonaer Str. 22, 10557 Berlin, Allemagne",
    "category": "Quartiers & ambiances",
    "quarter": "Hansaviertel",
    "note": "Musée à ciel ouvert de l’Interbau 1957, avec Aalto, Niemeyer, Gropius et autres modernistes.",
    "photoQuery": "Hansaviertel Berlin Interbau",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 16,
    "name": "Tour radio de Berlin",
    "address": "Hammarskjöldpl., 14055 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Westend",
    "note": "Grande structure métallique du Funkturm, intéressante en contre-plongée et à l’heure bleue.",
    "photoQuery": "Funkturm Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 17,
    "name": "Klunkerkranich",
    "address": "Karl-Marx-Straße 66, 12043 Berlin-Bezirk Neukölln, Allemagne",
    "category": "Cafés & bars",
    "quarter": "Neukölln",
    "note": "Rooftop alternatif avec vue urbaine, structures bricolées et lumière de fin de journée.",
    "photoQuery": "Klunkerkranich Berlin rooftop",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 18,
    "name": "Badeschiff",
    "address": "Eichenstraße 4, 12435 Berlin-Bezirk Friedrichshain-Kreuzberg, Allemagne",
    "category": "Quartiers & ambiances",
    "quarter": "Alt-Treptow",
    "note": "Piscine flottante sur la Spree, containers, eau et paysage industriel.",
    "photoQuery": "Badeschiff Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 19,
    "name": "Shell-Haus",
    "address": "Reichpietschufer 60-62, 10785 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Tiergarten",
    "note": "Façade ondulée emblématique de la Nouvelle Objectivité.",
    "photoQuery": "Shell Haus Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 20,
    "name": "Dong Xuan Center",
    "address": "Herzbergstraße 128-139, 10365 Bezirk Lichtenberg, Allemagne",
    "category": "Quartiers & ambiances",
    "quarter": "Lichtenberg",
    "note": "Halles vietnamiennes, enseignes, couleurs et atmosphère très différente du centre de Berlin.",
    "photoQuery": "Dong Xuan Center Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 21,
    "name": "St. Agnes",
    "address": "Alexandrinenstraße 118-121, 10969 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Kreuzberg",
    "note": "Ancienne église brutaliste transformée en galerie : béton monumental et lumière austère.",
    "photoQuery": "St Agnes Berlin König Galerie",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 22,
    "name": "Kulturforum",
    "address": "Matthäikirchplatz, 10785 Berlin, Allemagne",
    "category": "Culture & musées",
    "quarter": "Tiergarten",
    "note": "Ensemble culturel moderniste : espaces ouverts, musées et grands volumes.",
    "photoQuery": "Kulturforum Berlin architecture",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 23,
    "name": "Philharmonie de Berlin",
    "address": "Herbert-von-Karajan-Straße 1, 10785 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Tiergarten",
    "note": "Hans Scharoun : formes organiques, toiture dorée et architecture expressionniste.",
    "photoQuery": "Berliner Philharmonie Scharoun",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 24,
    "name": "Kammermusiksaal - Berlin",
    "address": "Herbert-von-Karajan-Straße 1, 10785 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Tiergarten",
    "note": "Salle de musique aux volumes géométriques, complément naturel de la Philharmonie.",
    "photoQuery": "Kammermusiksaal Berlin architecture",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 25,
    "name": "Musée des arts décoratifs",
    "address": "Matthäikirchplatz, 10785 Berlin, Allemagne",
    "category": "Culture & musées",
    "quarter": "Tiergarten",
    "note": "Le Kunstgewerbemuseum de Rolf Gutbrod : modernisme tardif et intérieurs graphiques.",
    "photoQuery": "Kunstgewerbemuseum Berlin Kulturforum",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 26,
    "name": "Sony-Center",
    "address": "Potsdamer Platz, 10785 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Potsdamer Platz",
    "note": "Le désormais Center am Potsdamer Platz : spectaculaire toiture tendue, verre et lumière nocturne.",
    "photoQuery": "Sony Center Berlin Potsdamer Platz roof",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 27,
    "name": "Tempelhofer Feld",
    "address": "Columbiadamm 124, 10965 Berlin, Allemagne",
    "category": "Quartiers & ambiances",
    "quarter": "Tempelhof",
    "note": "Ancien aéroport devenu parc immense : pistes, horizon dégagé et architecture monumentale.",
    "photoQuery": "Tempelhofer Feld Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 28,
    "name": "Berghain",
    "address": "Am Wriezener Bahnhof, 10243 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Friedrichshain",
    "note": "Ancienne centrale électrique, façade industrielle monumentale et atmosphère brute.",
    "photoQuery": "Berghain Berlin building",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 29,
    "name": "RAW-Gelände",
    "address": "Revaler Str. 99, 10245 Berlin, Allemagne",
    "category": "Quartiers & ambiances",
    "quarter": "Friedrichshain",
    "note": "Friches ferroviaires, street art, briques et culture alternative.",
    "photoQuery": "RAW Gelände Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 30,
    "name": "East Side Gallery",
    "address": "Mühlenstraße, 10243 Berlin, Allemagne",
    "category": "Quartiers & ambiances",
    "quarter": "Friedrichshain",
    "note": "Mur, fresques et longues perspectives urbaines au bord de la Spree.",
    "photoQuery": "East Side Gallery Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 31,
    "name": "Oberbaumbrücke",
    "address": "Oberbaumbrücke, 10243 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Friedrichshain / Kreuzberg",
    "note": "Pont néogothique iconique, arches, métro et vues sur la Spree.",
    "photoQuery": "Oberbaumbrücke Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 32,
    "name": "Paulsternstr.",
    "address": "Paulsternstraße / Nonnendammallee, 13599 Berlin, Allemagne",
    "category": "Métro & transport",
    "quarter": "Spandau",
    "note": "Station U7 très colorée des années 1980, idéale pour lignes, symétries et ambiance rétro.",
    "photoQuery": "U Bahnhof Paulsternstrasse Berlin",
    "lat": 52.53806,
    "lng": 13.24747,
    "source": "Google Maps export"
  },
  {
    "id": 33,
    "name": "Rohrdamm",
    "address": "Rohrdamm, 13629 Berlin, Allemagne",
    "category": "Métro & transport",
    "quarter": "Siemensstadt",
    "note": "Station U7 au graphisme marqué, carreaux et esthétique industrielle.",
    "photoQuery": "U Bahnhof Rohrdamm Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 34,
    "name": "Galerie James Simon",
    "address": "Bodestraße 1-3, 10178 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "David Chipperfield : colonnade contemporaine et dialogue avec l’Île aux Musées.",
    "photoQuery": "James Simon Galerie Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 35,
    "name": "Fehrbelliner Platz",
    "address": "10707 Berlin, Allemagne",
    "category": "Métro & transport",
    "quarter": "Wilmersdorf",
    "note": "Ensemble urbain et station aux couleurs fortes, typique de Berlin-Ouest.",
    "photoQuery": "U Bahnhof Fehrbelliner Platz Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 36,
    "name": "Marie-Elisabeth-Lüders-Haus",
    "address": "Adele-Schreiber-Krieger-Straße 1, 10117 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "Architecture du Bundestag au bord de la Spree, grandes lignes et ouvertures circulaires.",
    "photoQuery": "Marie Elisabeth Lüders Haus Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 37,
    "name": "FORUM KUNST im Bundestag",
    "address": "Luisenstraße 30, 10117 Berlin, Allemagne",
    "category": "Culture & musées",
    "quarter": "Mitte",
    "note": "Art contemporain au cœur du quartier parlementaire.",
    "photoQuery": "Forum Kunst im Bundestag Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 38,
    "name": "Maison des cultures du monde",
    "address": "John-Foster-Dulles-Allee 10, 10557 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Tiergarten",
    "note": "La “Schwangere Auster” : toit courbe spectaculaire et bassin réfléchissant.",
    "photoQuery": "Haus der Kulturen der Welt Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 39,
    "name": "Paul Loebe Building",
    "address": "Konrad-Adenauer-Straße 1, 10557 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "Façades vitrées, cylindres et passerelles dans le complexe parlementaire.",
    "photoQuery": "Paul Löbe Haus Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 40,
    "name": "3XN Cube Berlin",
    "address": "Washingtonpl. 3, 10557 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Hauptbahnhof",
    "note": "Cube de verre miroir face à la Hauptbahnhof : reflets et déformations de la ville.",
    "photoQuery": "Cube Berlin 3XN",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 41,
    "name": "Bierpinsel",
    "address": "Schloßstraße 17, 12163 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Steglitz",
    "note": "Tour pop-futuriste des années 1970, l’un des objets architecturaux les plus étranges de Berlin.",
    "photoQuery": "Bierpinsel Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 42,
    "name": "Kantgaragenpalast",
    "address": "Kant-Garage, Kantstraße 127, 10625 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Charlottenburg",
    "note": "Garage moderniste aux rampes hélicoïdales et façade industrielle.",
    "photoQuery": "Kant Garagen Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 43,
    "name": "Ludwig Erhard Haus",
    "address": "Fasanenstraße 85, 10623 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Charlottenburg",
    "note": "Architecture high-tech surnommée “Armadillo”, charpente métallique spectaculaire.",
    "photoQuery": "Ludwig Erhard Haus Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 44,
    "name": "ICC",
    "address": "Messedamm, 14055 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Westend",
    "note": "Vaisseau spatial brutaliste/high-tech, immense et très photogénique depuis l’extérieur.",
    "photoQuery": "ICC Berlin architecture",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 45,
    "name": "Minimal Bar",
    "address": "Rigaer Str. 31, 10247 Berlin-Bezirk Friedrichshain-Kreuzberg, Allemagne",
    "category": "Cafés & bars",
    "quarter": "Friedrichshain",
    "note": "Bar berlinois décontracté, ping-pong, lumière tamisée et ambiance locale.",
    "photoQuery": "Minimal Bar Berlin Rigaer",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 46,
    "name": "Musée Futurium",
    "address": "Alexanderufer 2, 10117 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "Façade métallique, lignes futuristes et skywalk sur le toit.",
    "photoQuery": "Futurium Berlin architecture",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 47,
    "name": "Rüyam Gemüse Kebab",
    "address": "Hauptstraße 36, 10827 Berlin, Allemagne",
    "category": "Manger & boire",
    "quarter": "Schöneberg",
    "note": "Adresse populaire pour un döner berlinois, utile comme pause gourmande.",
    "photoQuery": "Rüyam Gemüse Kebab Hauptstraße Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 48,
    "name": "Rüyam Gemüse Kebab",
    "address": "Schönhauser Allee 44A, 10435 Berlin-Bezirk Pankow, Allemagne",
    "category": "Manger & boire",
    "quarter": "Prenzlauer Berg",
    "note": "Adresse populaire pour un döner berlinois, utile comme pause gourmande.",
    "photoQuery": "Rüyam Gemüse Kebab Schönhauser Allee Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 49,
    "name": "Deutsche Kinemathek",
    "address": "Mauerstraße 79, 10117 Berlin, Allemagne",
    "category": "Culture & musées",
    "quarter": "Mitte",
    "note": "Cinéma, photographie et archives : nouvelle implantation centrale.",
    "photoQuery": "Deutsche Kinemathek Berlin Mauerstrasse",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 50,
    "name": "KAOS Berlin",
    "address": "Wilhelminenhofstraße 92, 12459 Berlin-Bezirk Treptow-Köpenick, Allemagne",
    "category": "Quartiers & ambiances",
    "quarter": "Oberschöneweide",
    "note": "Espace créatif au bord de la Spree dans un environnement industriel.",
    "photoQuery": "KAOS Berlin Wilhelminenhofstrasse",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 51,
    "name": "kioski",
    "address": "Köpenicker Str. 20, 10997 Berlin, Allemagne",
    "category": "Manger & boire",
    "quarter": "Kreuzberg",
    "note": "Petite adresse urbaine à garder comme halte dans la zone Kreuzberg.",
    "photoQuery": "kioski Berlin Köpenicker Strasse",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 52,
    "name": "K67 BERLIN",
    "address": "Leipziger Str. 61, 10117 Berlin, Allemagne",
    "category": "Auto & insolite",
    "quarter": "Mitte",
    "note": "Petit objet de design urbain/K67 à repérer pour son esthétique rétro-futuriste.",
    "photoQuery": "K67 Berlin kiosk design",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 53,
    "name": "Das Kleine Grosz Museum",
    "address": "Bülowstraße 18, 10783 Berlin, Allemagne",
    "category": "Culture & musées",
    "quarter": "Schöneberg",
    "note": "Petit musée dédié à George Grosz dans une ancienne station-service reconvertie.",
    "photoQuery": "Das Kleine Grosz Museum Berlin",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 54,
    "name": "Berolinahaus",
    "address": "Berolinahaus, Alexanderpl. 1, 10178 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Mitte",
    "note": "Peter Behrens à Alexanderplatz : Nouvelle Objectivité, trame répétitive et histoire berlinoise.",
    "photoQuery": "Berolinahaus Berlin Alexanderplatz",
    "lat": null,
    "lng": null,
    "source": "Google Maps export"
  },
  {
    "id": 55,
    "name": "Kath. Gemeinde St. Martin Berlin-Kaulsdorf",
    "address": "Nentwigstraße 1, 12621 Berlin, Allemagne",
    "category": "Architecture & photo",
    "quarter": "Kaulsdorf",
    "note": "Église de 1929-30 en brique, entre expressionnisme et Nouvelle Objectivité.",
    "photoQuery": "St Martin Kirche Berlin Kaulsdorf",
    "lat": 52.5149,
    "lng": 13.60363,
    "source": "Google Maps export"
  }
];
